version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=debug
      # Uncomment to use Postgres
      # - DATABASE_URL=postgres://postgres:postgres@db:5432/telemetry
    restart: unless-stopped
    # Uncomment to enable postgres db
    # depends_on:
    #   - db
      
  # Uncomment to add a Postgres database
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=telemetry
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # CLI tool container - can be used to send test data
  telemetry-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/telemetry-cli simulate -u http://api:8080 -d device-simulator -i 10
    restart: unless-stopped
    depends_on:
      - api

# Uncomment to add a Postgres database
# volumes:
#   postgres_data: 